-- tymlee: per-user time log. Run once in the Supabase SQL editor.

create table if not exists public.entries (
  id         uuid primary key,             -- generated by the client so offline writes are idempotent
  user_id    uuid not null default auth.uid() references auth.users (id) on delete cascade,
  ts         bigint not null,               -- start time, milliseconds since the Unix epoch
  text       text not null check (char_length(text) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists entries_user_ts_idx on public.entries (user_id, ts);

-- Every signed-in user can see and change only their own rows.
alter table public.entries enable row level security;

drop policy if exists "entries: read own" on public.entries;
create policy "entries: read own" on public.entries
  for select to authenticated using (user_id = (select auth.uid()));

drop policy if exists "entries: insert own" on public.entries;
create policy "entries: insert own" on public.entries
  for insert to authenticated with check (user_id = (select auth.uid()));

drop policy if exists "entries: update own" on public.entries;
create policy "entries: update own" on public.entries
  for update to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

drop policy if exists "entries: delete own" on public.entries;
create policy "entries: delete own" on public.entries
  for delete to authenticated using (user_id = (select auth.uid()));

revoke all on public.entries from anon;
grant select, insert, update, delete on public.entries to authenticated;

-- ---------------------------------------------------------------------------
-- End-to-end encryption (added later; safe to run on an existing project).
-- Entry text is now stored encrypted, which is longer than the plain text.

alter table public.entries drop constraint if exists entries_text_check;
alter table public.entries add constraint entries_text_check check (char_length(text) between 1 and 16000);

-- One row per user holding the account's master key, but only in locked form:
-- `recovery` is locked with the recovery key, `link` briefly with a /link
-- code. Both codes stay on the user's devices, so this table can't be used
-- to read anyone's entries.
create table if not exists public.keyring (
  user_id    uuid primary key default auth.uid() references auth.users (id) on delete cascade,
  recovery   jsonb not null,
  link       jsonb,
  created_at timestamptz not null default now()
);

alter table public.keyring enable row level security;

drop policy if exists "keyring: read own" on public.keyring;
create policy "keyring: read own" on public.keyring
  for select to authenticated using (user_id = (select auth.uid()));

drop policy if exists "keyring: insert own" on public.keyring;
create policy "keyring: insert own" on public.keyring
  for insert to authenticated with check (user_id = (select auth.uid()));

drop policy if exists "keyring: update own" on public.keyring;
create policy "keyring: update own" on public.keyring
  for update to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

revoke all on public.keyring from anon;
grant select, insert, update on public.keyring to authenticated;

-- ---------------------------------------------------------------------------
-- Change tracking (added later; safe to run on an existing project).
-- The database stamps every insert and update with modified_at, and deleted
-- entries leave a marker (deleted = true, no content) instead of vanishing.
-- Devices then ask only for rows changed since their last check, which also
-- lets encrypted entries keep their start time inside the encryption.

alter table public.entries add column if not exists modified_at timestamptz not null default now();
alter table public.entries add column if not exists deleted boolean not null default false;
create index if not exists entries_user_modified_idx on public.entries (user_id, modified_at);

create or replace function public.entries_touch() returns trigger
language plpgsql set search_path = '' as $$
begin
  new.modified_at := clock_timestamp();
  return new;
end;
$$;

drop trigger if exists entries_touch on public.entries;
create trigger entries_touch before insert or update on public.entries
  for each row execute function public.entries_touch();

-- ---------------------------------------------------------------------------
-- Notes on entries (added later; safe to run on an existing project).
-- Encrypted accounts keep notes inside the encrypted entry text, which is why
-- the text limit above allows 16000; accounts without encryption use this
-- column.

alter table public.entries add column if not exists notes text;
alter table public.entries drop constraint if exists entries_notes_check;
alter table public.entries add constraint entries_notes_check check (notes is null or char_length(notes) <= 8000);
