const { chromium } = require('playwright');
const S = process.argv[2];
const ok = (c, m) => { console.log((c ? 'PASS ' : 'FAIL ') + m); if (!c) process.exitCode = 1; };
(async () => {
  const b = await chromium.launch();
  const ctx = await b.newContext({ viewport: { width: 1000, height: 700 }, serviceWorkers: 'block' });
  await ctx.route('**/config.js', (r) => r.fulfill({ contentType: 'text/javascript', body: '' }));
  const p = await ctx.newPage();
  const errs = []; p.on('pageerror', (e) => errs.push(e.message));
  await p.goto('http://localhost:8123/'); await p.evaluate(() => localStorage.setItem('tymlee.view2', 'cli')); await p.reload(); await p.waitForTimeout(400);
  const send = async (t) => { await p.fill('#entry', t); await p.press('#entry', 'Enter'); await p.waitForTimeout(150); };
  await send('/todo NORTHSTAR send the stems to the label');
  await send('/todo ACME call about the drawings');
  await send('/todo admin timesheets');
  await send('/clear');
  await p.fill('#entry', '/do '); await p.waitForTimeout(100);
  ok((await p.locator('#matches span').allTextContents()).join('|') === '/do 10 NORTHSTAR send the stems to the label|/do 20 ACME call about the drawings|/do 30 admin timesheets', `all open to-dos with text: ${(await p.locator('#matches span').allTextContents()).join('|')}`);
  await p.fill('#entry', '/do draw'); await p.waitForTimeout(100);
  ok((await p.locator('#matches span').allTextContents()).join('|') === '/do 20 ACME call about the drawings', 'a word finds the to-do');
  ok((await p.locator('#ghost').textContent()) === '', 'no ghost text when it does not continue what was typed');
  await p.press('#entry', 'Tab'); await p.waitForTimeout(100);
  ok((await p.inputValue('#entry')) === '/do 20 ', `Tab completes the ID: "${await p.inputValue('#entry')}"`);
  await p.fill('#entry', '/do 2'); await p.waitForTimeout(100);
  await p.screenshot({ path: `${S}/v17-complete.png` });
  ok((await p.locator('#ghost').textContent()).includes('/do 20'), 'digits ghost-complete');
  await send('/do 20'); await send('/done 20');
  await p.fill('#entry', '/undone '); await p.waitForTimeout(100);
  ok((await p.locator('#matches span').allTextContents()).join('|').startsWith('/undone 20'), '/undone offers done ones');
  ok(!errs.length, 'no errors ' + errs.join('|'));
  await b.close();
})();
