const { chromium, devices } = require('playwright');
const S = process.argv[2];
const ok = (c, m) => { console.log((c ? 'PASS ' : 'FAIL ') + m); if (!c) process.exitCode = 1; };
const at = (hm) => new Date(`2026-10-01T${hm}:00-04:00`).getTime();
(async () => {
  const b = await chromium.launch();
  const errs = [];
  const ctx = await b.newContext({ viewport: { width: 1100, height: 760 }, timezoneId: 'America/New_York', serviceWorkers: 'block' });
  await ctx.clock.install({ time: new Date('2026-10-01T13:40:00-04:00') });
  await ctx.route('**/config.js', (r) => r.fulfill({ contentType: 'text/javascript', body: '' }));
  const p = await ctx.newPage();
  p.on('pageerror', (e) => errs.push(e.message));
  await p.goto('http://localhost:8123/index.html');
  await p.evaluate((r) => { localStorage.setItem('tymlee.v2.local.entries', JSON.stringify(r)); localStorage.setItem('tymlee.view2', 'cli'); }, [{ id: 'a', ts: at('09:00'), text: 'NORTHSTAR mix revisions' }, { id: 'b', ts: at('13:00'), text: 'NORTHSTAR stems for the label' }]);
  await p.reload(); await p.waitForTimeout(600);
  const send = async (t) => { await p.fill('#entry', t); await p.press('#entry', 'Enter'); await p.waitForTimeout(200); };
  const last = () => p.locator('#out pre').last().textContent();
  const files = () => p.evaluate(() => JSON.parse(tymleeStorage.getItem('tymlee.v2.local.entries')).pop().files || '');
  await send('/clear');
  await send('/file /Volumes/Work/NORTHSTAR/ stems.zip mix_v7.wav, ref.wav');
  ok((await files()) === '/Volumes/Work/NORTHSTAR/stems.zip\n/Volumes/Work/NORTHSTAR/mix_v7.wav\n/Volumes/Work/NORTHSTAR/ref.wav', 'a folder then its files: stored as full paths');
  ok((await last()).startsWith('@ /Volumes/Work/NORTHSTAR/ stems.zip mix_v7.wav ref.wav\n3 files added to ID:000020'), `the reply shows them grouped: ${await last()}`);
  await send('/file /Volumes/Work/NORTHSTAR/ stems.zip /Volumes/Work/refs/ ref_a.wav');
  ok((await files()).split('\n').length === 4, 'a path already there is not added twice');
  await send('/log');
  const log = await last();
  ok(log.includes('@ /Volumes/Work/NORTHSTAR/ stems.zip mix_v7.wav ref.wav') && log.includes('@ /Volumes/Work/refs/ref_a.wav'), `/log shows folders with their files: ${log}`);
  await send('/newform delivery');
  await p.locator('#out .editor').fill('%{files}\n--\n%{paths}');
  await p.locator('#out .editor').press('Control+Enter'); await p.waitForTimeout(200);
  await send('/form delivery');
  ok((await last()).includes('/Volumes/Work/NORTHSTAR/\n  stems.zip\n  mix_v7.wav\n  ref.wav\n/Volumes/Work/refs/ref_a.wav\n--\n/Volumes/Work/NORTHSTAR/stems.zip'), `%{files} lists a folder with its files under it; %{paths} in full: ${JSON.stringify(await last())}`);
  await p.screenshot({ path: `${S}/files-cli.png` });
  // /edit round trip keeps them.
  await send('/edit');
  const ed = await p.locator('#out .editor').inputValue();
  ok(ed.includes('@ /Volumes/Work/NORTHSTAR/ stems.zip mix_v7.wav ref.wav'), '/edit shows them grouped');
  await p.locator('#out .editor').press('Control+Enter'); await p.waitForTimeout(300);
  ok((await files()).split('\n').length === 4, '/edit saved unchanged keeps all four');
  // The GUI card.
  await p.evaluate(() => localStorage.setItem('tymlee.view2', 'pure')); await p.reload(); await p.waitForTimeout(700);
  await p.locator('.tl-block', { hasText: 'stems for the label' }).click(); await p.waitForTimeout(300);
  const area = p.locator('.entry-card textarea').last();
  ok((await area.inputValue()) === '/Volumes/Work/NORTHSTAR/ stems.zip mix_v7.wav ref.wav\n/Volumes/Work/refs/ref_a.wav', `the card shows them grouped: ${JSON.stringify(await area.inputValue())}`);
  await area.fill('/Volumes/Work/NORTHSTAR/\nstems.zip\nfinal.wav');
  await p.screenshot({ path: `${S}/files-card.png` });
  await p.locator('.entry-card button[type=submit]').click(); await p.waitForTimeout(300);
  ok((await files()) === '/Volumes/Work/NORTHSTAR/stems.zip\n/Volumes/Work/NORTHSTAR/final.wav', 'the card takes a folder on one line and its files on the next');
  ok(!errs.length, 'no page errors ' + errs.join(' | '));
  await b.close();
})();
