const { chromium } = require('playwright');
const S = process.argv[2];
const ok = (c, m) => { console.log((c ? 'PASS ' : 'FAIL ') + m); if (!c) process.exitCode = 1; };
(async () => {
  const b = await chromium.launch();
  const ctx = await b.newContext({ viewport: { width: 900, height: 700 } });
  await ctx.route('**/config.js', (r) => r.fulfill({ contentType: 'text/javascript', body: '' }));
  const p = await ctx.newPage();
  const errs = []; p.on('pageerror', (e) => errs.push(e.message));
  await p.goto('http://localhost:8123/index.html');
  const send = async (x) => { await p.fill('#entry', x); await p.press('#entry', 'Enter'); await p.waitForTimeout(100); };
  const last = async () => (await p.locator('#out pre').allTextContents()).slice(-1)[0];
  const status = () => p.locator('#status').innerText();

  await send('/off');
  ok((await last()).includes('not clocked in'), '/off with nothing running');
  await send('dev fixing login bug');
  await send('/off');
  ok(/out dev \(0:00\)  off$/.test(await last()), `/off output: ${await last()}`);
  ok((await status()).includes('■ off') && !(await status()).includes('▶'), `status shows off: ${await status()}`);
  await send('/off');
  ok((await last()).includes('not clocked in'), 'second /off refused');
  await send('/undo');
  ok((await last()).includes('resumed dev fixing login bug'), `/undo resumes: ${await last()}`);
  ok((await status()).includes('▶'), 'status running again');
  await send('/off');
  await send('mtg standup');
  ok(/^\d\d:\d\d  in ID:000030 mtg standup$/.test(await last()), `clock in after off has no "out": ${await last()}`);
  await send('/log');
  const log = await last();
  ok(/\n  ID:000020  \d\d:\d\d  \d\d:\d\d       -  \(off\)\n/.test(log), 'report shows the off row');
  ok(!/\(off\)\s+\d+:\d\d\s+\d+%/.test(log), 'off not in the summary');
  await p.fill('#entry', '/o'); await p.press('#entry', 'Tab');
  ok((await p.inputValue('#entry')) === '/off ', 'Tab completes /off');
  await p.fill('#entry', ''); await p.fill('#entry', 'o');
  ok(!(await p.locator('#matches').innerText()).includes('/off'), '/off is not offered as a category');
  await send('/edit');
  ok((await p.locator('#out .editor').inputValue()).includes('/off'), '/edit shows the off line');
  await send('/cancel');
  await p.screenshot({ path: `${S}/off.png` });
  ok(errs.length === 0, `no page errors ${errs}`);
  await b.close();
})();
