const { chromium, devices } = require('playwright');
const ok = (c, m) => { console.log((c ? 'PASS ' : 'FAIL ') + m); if (!c) process.exitCode = 1; };
(async () => {
  const b = await chromium.launch();
  const errs = [];
  const open = async (opts) => {
    const ctx = await b.newContext(opts);
    await ctx.route('**/config.js', (r) => r.fulfill({ contentType: 'text/javascript', body: '' }));
    await ctx.addInitScript(() => { new MutationObserver(() => document.querySelectorAll('.gmenu-group:not(.open)').forEach((g) => g.classList.add('open'))).observe(document, { childList: true, subtree: true }); }); // tests: every menu section open
    const p = await ctx.newPage();
    p.on('pageerror', (e) => errs.push(e.message));
    await p.goto('http://localhost:8123/index.html'); await p.waitForTimeout(300);
    p.entries = () => p.evaluate(() => JSON.parse(tymleeStorage.getItem('tymlee.v2.local.entries') || '[]').map((e) => e.text));
    p.toast = () => p.locator('.toast').last().textContent();
    p.startWith = async (c, t) => { if (await p.locator('.sb-new').isVisible()) await p.click('.sb-new'); await p.fill('.sb-cat input', c); await p.fill('.sb-title', t); await p.click('.sb-start'); await p.waitForTimeout(350); };
    return p;
  };
  const p = await open({ viewport: { width: 1100, height: 750 } });
  ok(await p.locator('#startbar').isHidden(), 'Hybrid is still the default');
  await p.locator('#status .view-toggle button[aria-label="GUI"]').click(); await p.waitForTimeout(300);
  ok(await p.locator('#startbar').isVisible() && await p.locator('#gui').isVisible() && await p.locator('#out').isHidden() && await p.locator('#entry').isHidden(), 'GUI: timeline and start bar, no console or prompt');
  ok(await p.locator('.sb-off').isHidden() && await p.locator('#startbar').getAttribute('data-mode') === 'idle', 'nothing running: the fields and Start, no Off');
  await p.click('.sb-start'); await p.waitForTimeout(200);
  ok((await p.toast()).includes('Choose a category first'), 'Start without a category explains');
  await p.startWith('dev', 'fix the export');
  ok((await p.entries()).join() === 'dev fix the export' && (await p.toast()).includes('in ID:000010 dev fix the export') && (await p.toast()).includes('Undo'), 'Start adds the entry; the toast offers Undo');
  await p.click('.sb-new');
  ok((await p.locator('.sb-cat input').inputValue()) === '' && (await p.locator('.sb-title').inputValue()) === '', 'the fields clear');
  await p.locator('.sb-cat input').click(); await p.locator('.sb-cat input').type('m'); await p.waitForTimeout(100);
  ok(await p.locator('.sb-suggest').isHidden(), 'no suggestion for a new category');
  await p.fill('.sb-cat input', ''); await p.locator('.sb-cat input').type('d'); await p.waitForTimeout(100);
  ok((await p.locator('.sb-opt').allTextContents()).join() === 'dev', 'typing shows matching categories');
  await p.keyboard.press('ArrowDown'); await p.keyboard.press('Enter'); await p.waitForTimeout(100);
  ok((await p.locator('.sb-cat input').inputValue()) === 'dev' && await p.evaluate(() => document.activeElement.classList.contains('sb-title')), 'arrow + Enter picks it and moves to the title');
  await p.keyboard.type('second thing'); await p.keyboard.press('Enter'); await p.waitForTimeout(350);
  ok((await p.entries()).length === 2, 'Enter in the title starts it');
  await p.locator('.toast-action').last().click(); await p.waitForTimeout(350);
  ok((await p.entries()).length === 1, 'Undo in the toast removes it');
  await p.click('.sb-new');
  await p.fill('.sb-cat input', 'client work'); await p.waitForTimeout(50);
  ok((await p.locator('.sb-cat input').inputValue()) === 'client-work', 'a category stays one word');
  await p.fill('.sb-cat input', '');
  await p.click('.sb-cancel');
  await p.click('.sb-off'); await p.waitForTimeout(350);
  ok((await p.entries()).pop() === '/off' && await p.locator('.sb-off').isHidden(), 'Off clocks out');
  // Menu
  await p.click('.sb-menu'); await p.waitForTimeout(200);
  ok(await p.locator('.gmenu').isVisible() && (await p.locator('.gmenu-about').textContent()).startsWith('tymlee v'), 'the menu opens, with the version');
  await p.getByRole('button', { name: 'Rate and overtime' }).click(); await p.waitForTimeout(300);
  await p.fill('input[name=rate]', '30'); await p.fill('input[name=otmin]', '40'); await p.click('.gform-go'); await p.waitForTimeout(500);
  await p.click('.sb-menu'); await p.getByRole('button', { name: 'Rate and overtime' }).click(); await p.waitForTimeout(300);
  ok((await p.inputValue('input[name=rate]')) === '30' && (await p.inputValue('input[name=otmin]')) === '40', 'pay settings saved (the form shows them again)');
  await p.keyboard.press('Escape'); await p.waitForTimeout(200);
  ok(!(await p.locator('.gsheet').count()), 'Esc closes a sheet');
  await p.startWith('dev', 'third');
  await p.click('.sb-menu'); await p.getByRole('button', { name: 'Add a note' }).click(); await p.waitForTimeout(300);
  await p.fill('input[name=text]', 'from the menu'); await p.click('.gform-go'); await p.waitForTimeout(400);
  ok(await p.evaluate(() => JSON.parse(tymleeStorage.getItem('tymlee.v2.local.entries')).pop().notes === 'from the menu'), 'Note on the current entry');
  await p.click('.sb-menu'); await p.getByRole('button', { name: 'Link to a category' }).first().click(); await p.waitForTimeout(300);
  await p.fill('input[name=category]', 'dev'); await p.fill('input[name=wo]', '4471'); await p.click('.gform-go'); await p.waitForTimeout(400);
  ok(await p.evaluate(() => JSON.parse(tymleeStorage.getItem('tymlee.v2.local.entries')).filter((e) => e.wo === '4471').length >= 2), 'Link a work order');
  await p.click('.sb-menu'); await p.getByRole('button', { name: 'Log', exact: true }).click(); await p.waitForTimeout(300);
  await p.click('.gform-go'); await p.waitForTimeout(400);
  ok((await p.locator('.gsheet-title').textContent()) === 'Log' && (await p.locator('.gsheet-text').first().textContent()).includes('third'), 'Log shows in a sheet');
  await p.click('.gsheet-close'); await p.waitForTimeout(200);
  // /edit goes through the CLI view and comes back
  await p.click('.sb-menu'); await p.getByRole('button', { name: 'Edit entries' }).click(); await p.waitForTimeout(500);
  ok(await p.locator('#out .editor').isVisible() && await p.locator('#startbar').isHidden(), 'Edit entries as text opens the text box (CLI view)');
  ok(await p.locator('.editor-buttons .editor-save').isVisible() && (await p.locator('.editor-buttons button').allTextContents()).join() === 'Save,Cancel', 'with Save and Cancel buttons');
  await p.locator('.editor-buttons button', { hasText: 'Cancel' }).click(); await p.waitForTimeout(400);
  ok(await p.locator('#startbar').isVisible() && !(await p.locator('.editor-buttons').count()), 'Cancel comes back to the GUI view');
  await p.click('.sb-menu'); await p.getByRole('button', { name: 'Edit entries' }).click(); await p.waitForTimeout(500);
  const box = p.locator('#out .editor');
  await box.fill((await box.inputValue()).replace('dev third', 'dev third, edited'));
  await p.locator('.editor-save').click(); await p.waitForTimeout(500);
  ok(await p.locator('#startbar').isVisible() && (await p.entries()).includes('dev third, edited'), 'Save applies the edit and comes back');
  await p.click('.sb-menu'); await p.getByRole('button', { name: 'Export' }).click(); await p.waitForTimeout(300);
  ok((await p.locator('.gform-range[aria-pressed="true"]').allTextContents()).join() === 'Text,Today', 'Export: a Text / CSV choice and a range');
  const dl = p.waitForEvent('download');
  await p.locator('.gform-range', { hasText: 'CSV' }).click(); await p.click('.gform-go');
  ok((await dl).suggestedFilename().endsWith('.csv'), 'CSV downloads a .csv');
  // Ctrl+Z outside fields
  const n = (await p.entries()).length;
  await p.locator('#gui').click({ position: { x: 5, y: 5 } }); await p.keyboard.press('Control+z'); await p.waitForTimeout(400);
  ok((await p.entries()).length === n - 1, 'Ctrl+Z undoes');
  await p.reload(); await p.waitForTimeout(500);
  ok(await p.locator('#startbar').isVisible(), 'the GUI view is remembered');
  await p.locator('#status .view-toggle button[aria-label="Hybrid"]').click(); await p.waitForTimeout(300);
  ok(await p.locator('#startbar').isHidden() && await p.locator('#out').isVisible() && await p.locator('#entry').isVisible(), 'Hybrid is back to timeline + console');
  // Phone
  const m = await open({ ...devices['iPhone 13'] });
  await m.locator('#status .view-toggle button[aria-label="GUI"]').tap(); await m.waitForTimeout(300);
  const bar = await m.locator('#startbar').boundingBox();
  ok(bar.height > 190 && bar.height < 250, `phone, nothing running: card, two fields, Resume and Start (${Math.round(bar.height)}px)`);
  await m.locator('.sb-cat input').tap(); await m.keyboard.type('gym'); await m.locator('.sb-start').tap(); await m.waitForTimeout(400);
  ok((await m.entries()).join() === 'gym', 'phone: start with just a category');
  ok(await m.evaluate(() => !document.activeElement || !['INPUT', 'TEXTAREA'].includes(document.activeElement.tagName)), 'phone: the keyboard goes away after Start');
  ok(errs.length === 0, `no page errors ${errs}`);
  await b.close();
})();
