const { chromium, devices } = require('playwright');
const S = process.argv[2];
const ok = (c, m) => { console.log((c ? 'PASS ' : 'FAIL ') + m); if (!c) process.exitCode = 1; };
const at = (hm) => new Date(`2026-10-01T${hm}:00-04:00`).getTime();
const seed = [
  { id: 'a', ts: at('08:00'), text: 'NORTHSTAR mix revisions', wo: '4471' },
  { id: 'b', ts: at('10:00'), text: 'ACME drawings' },
];
(async () => {
  const b = await chromium.launch();
  const errs = [];
  for (const [name, opts] of [['desktop', { viewport: { width: 1100, height: 820 } }], ['phone', { ...devices['iPhone 13'], viewport: { width: 390, height: 760 } }]]) {
    const ctx = await b.newContext({ ...opts, timezoneId: 'America/New_York' });
    await ctx.clock.install({ time: new Date('2026-10-01T13:40:00-04:00') });
    await ctx.route('**/config.js', (r) => r.fulfill({ contentType: 'text/javascript', body: '' }));
    const p = await ctx.newPage();
    p.on('pageerror', (e) => errs.push(e.message));
    await p.goto('http://localhost:8123/index.html');
    await p.evaluate((r) => { localStorage.setItem('tymlee.v2.local.entries', JSON.stringify(r)); localStorage.setItem('tymlee.view2', 'cli'); }, seed);
    await p.reload(); await p.waitForTimeout(600);
    const send = async (t) => { await p.fill('#entry', t); await p.press('#entry', 'Enter'); await p.waitForTimeout(250); };
    const last = () => p.locator('#out pre').last().textContent();
    const outText = () => p.locator('#out').textContent();
    const entries = () => p.evaluate(() => JSON.parse(tymleeStorage.getItem('tymlee.v2.local.entries') || '[]').map((e) => e.text));
    await send('/clear');
    await send('/todo NORTHSTAR send the stems to the label due:today');
    ok((await last()).includes('TD:000010 NORTHSTAR send the stems to the label · due today · /do 10 starts it'), `due:today on /todo: ${await last()}`);
    await send('/todo ACME call about the drawings due:fri');
    ok((await last()).includes('due tomorrow'), `due:fri on a Thursday: ${await last()}`);
    await send('/todo email invoice for September');
    await send('/todo admin timesheets due:soonish');
    ok((await last()).includes('"soonish" is not a day'), 'a bad day is refused');
    await send('/due 30 09-29');
    ok((await last()).includes('TD:000030 email invoice for September · overdue, was due Tue 09-29'), `/due: ${await last()}`);
    await send('/todos today');
    const today = await last();
    ok(today.startsWith('due today: 2') && today.includes('TD:000010') && today.includes('TD:000030') && !today.includes('TD:000020'), `/todos today: ${today}`);
    await send('/done');
    ok((await last()).includes('/done alone marks the to-do you started with /do'), 'bare /done with nothing started explains');
    await send('/do 10');
    ok((await entries()).slice(-1)[0] === 'NORTHSTAR send the stems to the label', '/do starts an entry with the to-do text');
    ok((await outText()).includes('out ACME (3:40)') && (await outText()).includes('working on TD:000010'), '/do ends the running entry and says what it is working on');
    await send('/todos');
    const list = await last();
    ok(/\[>\] TD:000010 .*\(due today, working on it now\)/.test(list) && list.includes('to-do: 3 open, 1 overdue'), `/todos shows it running: ${list}`);
    if (name === 'desktop') await p.screenshot({ path: `${S}/v16-todos-cli.png` });
    await ctx.clock.runFor(25 * 60000);
    await send('/done');
    ok((await last()).includes('[x] TD:000010 NORTHSTAR send the stems'), `bare /done marks the started to-do: ${await last()}`);
    ok((await entries()).slice(-1)[0] === 'NORTHSTAR send the stems to the label' && (await entries()).length === 3, 'the entry keeps running (no new entry)');
    await send('/done');
    ok((await last()).includes('usage'), 'a second bare /done has nothing to mark');
    await send('/todos');
    ok(!(await last()).includes('send the stems'), '/todos leaves the done one out');
    await send('/todos done');
    ok((await last()).includes('done: 1') && (await last()).includes('[x] TD:000010'), `/todos done: the archive: ${await last()}`);
    await send('/due 20');
    ok((await last()).includes('no due day'), '/due with no day clears it');
    // The GUI: ▶ on a to-do.
    await p.evaluate(() => localStorage.setItem('tymlee.view2', 'pure')); await p.reload(); await p.waitForTimeout(600);
    await p.click('.sb-menu:visible, .tab[data-tab="menu"]:visible'); await p.waitForTimeout(200);
    await p.locator('.gmenu button', { hasText: 'To-do list' }).click(); await p.waitForTimeout(200);
    const rows = await p.locator('.gtick-row .gtick-text').allTextContents();
    ok(rows[0] === 'invoice for September', `overdue first in the sheet: ${rows}`);
    ok(await p.locator('.gtick-row.late').count() === 1, 'the overdue one is marked');
    await p.locator('.gtick-row', { hasText: 'call about the drawings' }).locator('.gtick-play').click(); await p.waitForTimeout(300);
    ok((await entries()).slice(-1)[0] === 'ACME call about the drawings', '▶ starts a timer for the to-do');
    ok(await p.locator('.gtick-row.now', { hasText: 'call about the drawings' }).count() === 1 && await p.locator('.gtick-row.now .gtick-play').count() === 0, 'the running one shows "working on it now", no ▶');
    await p.screenshot({ path: `${S}/v16-todos-gui-${name}.png` });
    await p.locator('.gtick-row', { hasText: 'call about the drawings' }).locator('input').check(); await p.waitForTimeout(200);
    ok((await entries()).slice(-1)[0] === 'ACME call about the drawings', 'ticking it off leaves the timer running');
    await p.click('.gsheet-close'); await p.waitForTimeout(300);
    await p.click('.sb-menu:visible, .tab[data-tab="menu"]:visible'); await p.waitForTimeout(200);
    await p.locator('.gmenu button', { hasText: 'To-do list' }).click(); await p.waitForTimeout(200);
    const after = await p.locator('.gtick-row .gtick-text').allTextContents();
    ok(!after.includes('call about the drawings') && !after.includes('send the stems to the label') && (await p.locator('.gform-range', { hasText: 'Done · 2' }).count()) === 1, `reopened, done ones are archived: ${after}`);
    await p.locator('.gform-range', { hasText: 'Done · 2' }).click(); await p.waitForTimeout(200);
    ok((await p.locator('.gtick-row .gtick-text').allTextContents()).join('|') === 'call about the drawings|send the stems to the label', 'the archive: latest done first');
    if (name === 'phone') await p.screenshot({ path: `${S}/v194-done-phone.png` });
    await p.locator('.gform-range', { hasText: 'Back to the list' }).click(); await p.waitForTimeout(200);
    await p.locator('.gform-range', { hasText: 'Add a to-do' }).click(); await p.waitForTimeout(200);
    await p.locator('.gform input').nth(0).fill('admin'); await p.locator('.gform input').nth(1).fill('timesheets');
    await p.locator('.gform input[type=date]').fill('2026-10-05');
    if (name === 'desktop') await p.screenshot({ path: `${S}/v16-todo-add.png` });
    await p.locator('.gform button[type=submit], .gform .gform-submit').first().click(); await p.waitForTimeout(300);
    ok((await p.locator('.gtick-row', { hasText: 'timesheets' }).textContent()).includes('due Mon 10-05'), 'the add form takes a due day');
    await ctx.close();
  }
  ok(!errs.length, 'no page errors ' + errs.join(' | '));
  await b.close();
})();
